apiVersion: 1.0.0
kind: ServiceAccount
data:
  # List of vaults which service account should have access to.
  vaults:
    - tntgtg7mwrf
    - tnturck9vro

  # Name of the Service Account.  
  name: vgs-org-api-test-v2

  # Scopes allow a Service Account to perform specific CLI commands.
  scopes:
    - name: access-logs:read
    - name: organizations:read
    - name: routes:write
    - name: vaults:write
    - name: organization-users:read
    - name: organization-users:write